### ISSUE TITLE
Opening dcm file from GE Healthcare sono device 

### ISSUE THREAD

**Issue by hema007-cmd** [JipengYan1995/SRUSSoftware#10]
Hey there :) 
I managed to open the software. I would like to open a dcm file from a device from GE Healthcare... would that be possible in the software or could you make it possible? 

Thank you so much:)

**Comment by JipengYan1995** [comment]
I do not have DICOM file from GE device and thus do not know the data format/variable names in the file. 

From my experience in operating DICOM files from Canon, Mindray and Philips, the variable name for images is the same but that for frame rate and pixel resolution sometimes is different.  You can try to use one of the three existing brands to load GE images and set frame rates and pixel resolution by yourself if those two parameters are not loaded.

If none of existing brands can load GE image data, I need your GE files to change the software accordingly.

**Comment by hema007-cmd** [comment]
Thanks so much! I tried and it worked! I would have to more questions. The result is saved as a mp4 video. Where are the Mat Files saved? And is it possible to save it as a new, corrected dicom video?
Thanks so much!

**Comment by JipengYan1995** [comment]
Mat files can be saved after activating the software. 

Resolution of videos generated in the processing seems not as important as source video.  MP4 costs much less space than DICOM and motion corrected frames are saved in mat file.

If you still think saving DICOM video is important for you, I can add this option in the software.

**Comment by hema007-cmd** [comment]
Thanks for the answer! The software creates an error after successfully managing the motion correction. I can export the corrected mp4 video in the results folder but can't generate .mat files. Would they be saved in the results folder as well? And would you know, why I can't generate them?

**Comment by hema007-cmd** [comment]
The error says: 
Error using pguArray. Failed to load graphics driver. Unable to load library "nvcdua.dll" The error was: Module can't be found, 
Update or reisntall ypur graphics driver

**Comment by hema007-cmd** [comment]
How do I "activate" the software then?

**Comment by JipengYan1995** [comment]
> How do I "activate" the software then?

It is described both in User Guide and Software Description. Please read the files.

**Comment by JipengYan1995** [comment]
> The error says: Error using pguArray. Failed to load graphics driver. Unable to load library "nvcdua.dll" The error was: Module can't be found, Update or reisntall ypur graphics driver

I have not met this problem before. It seems a problem of your GPU driver. You can try to solve it as the suggested.

**Comment by hema007-cmd** [comment]
I think its the activation, I just send you the System. Info file for activation. Thanks so much for the help!
