### ISSUE TITLE
Does this software require GPU?

### ISSUE THREAD

**Issue by li-liwen** [JipengYan1995/SRUSSoftware#7]
Issue type: question.

In the document, the tested environment has a RTX 3080 as the GPU accelerator. However, I didn't find anywhere explicitly stating that a GPU is required. In practice, the software would prompt some CUDA related errors when no GPU is present, but the overall result seems ok. Is GPU required or optional? Thank you for your time for answering my question.

**Comment by JipengYan1995** [comment]
Independent GPU is optional, only if you have an integrated GPU in your CPU. I did not incorporate any self-developed CUDA codes in the software to avoid dealing with various environment setup issues. Some Matlab functions will be accelerated if GPU is available.  The software might crush and quit if it is over the memory of GPU. Only if software runs, results with and without Independent GPU are the same.

**Comment by li-liwen** [comment]
@JipengYan1995 Thanks for the quick reply. I am using a server without integrated GPU in my CPU. I believe that I do need an independent GPU to make the software function properly in my case.

> I did not incorporate any self-developed CUDA codes in the software to avoid dealing with various environment setup issues.

I think I might have mistaken the GPU related prompt for CUDA related prompt. But I will consider a NVIDIA GPU nevertheless. Thank you for your attention and time for answering the question. I am closing this issue as I think my question has been answered.
